/*
Copyright 2019 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	time "time"

	openfaasv1alpha2 "github.com/openfaas-incubator/ingress-operator/pkg/apis/openfaas/v1alpha2"
	versioned "github.com/openfaas-incubator/ingress-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/openfaas-incubator/ingress-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha2 "github.com/openfaas-incubator/ingress-operator/pkg/client/listers/openfaas/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FunctionIngressInformer provides access to a shared informer and lister for
// FunctionIngresses.
type FunctionIngressInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.FunctionIngressLister
}

type functionIngressInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewFunctionIngressInformer constructs a new informer for FunctionIngress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFunctionIngressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFunctionIngressInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredFunctionIngressInformer constructs a new informer for FunctionIngress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFunctionIngressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpenfaasV1alpha2().FunctionIngresses(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpenfaasV1alpha2().FunctionIngresses(namespace).Watch(options)
			},
		},
		&openfaasv1alpha2.FunctionIngress{},
		resyncPeriod,
		indexers,
	)
}

func (f *functionIngressInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFunctionIngressInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *functionIngressInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&openfaasv1alpha2.FunctionIngress{}, f.defaultInformer)
}

func (f *functionIngressInformer) Lister() v1alpha2.FunctionIngressLister {
	return v1alpha2.NewFunctionIngressLister(f.Informer().GetIndexer())
}
