/*
Copyright 2019 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

// FunctionIngressListerExpansion allows custom methods to be added to
// FunctionIngressLister.
type FunctionIngressListerExpansion interface{}

// FunctionIngressNamespaceListerExpansion allows custom methods to be added to
// FunctionIngressNamespaceLister.
type FunctionIngressNamespaceListerExpansion interface{}
