/*
Copyright 2019 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/openfaas-incubator/ingress-operator/pkg/apis/openfaas/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFunctionIngresses implements FunctionIngressInterface
type FakeFunctionIngresses struct {
	Fake *FakeOpenfaasV1alpha2
	ns   string
}

var functioningressesResource = schema.GroupVersionResource{Group: "openfaas.com", Version: "v1alpha2", Resource: "functioningresses"}

var functioningressesKind = schema.GroupVersionKind{Group: "openfaas.com", Version: "v1alpha2", Kind: "FunctionIngress"}

// Get takes name of the functionIngress, and returns the corresponding functionIngress object, and an error if there is any.
func (c *FakeFunctionIngresses) Get(name string, options v1.GetOptions) (result *v1alpha2.FunctionIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(functioningressesResource, c.ns, name), &v1alpha2.FunctionIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.FunctionIngress), err
}

// List takes label and field selectors, and returns the list of FunctionIngresses that match those selectors.
func (c *FakeFunctionIngresses) List(opts v1.ListOptions) (result *v1alpha2.FunctionIngressList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(functioningressesResource, functioningressesKind, c.ns, opts), &v1alpha2.FunctionIngressList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.FunctionIngressList{ListMeta: obj.(*v1alpha2.FunctionIngressList).ListMeta}
	for _, item := range obj.(*v1alpha2.FunctionIngressList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested functionIngresses.
func (c *FakeFunctionIngresses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(functioningressesResource, c.ns, opts))

}

// Create takes the representation of a functionIngress and creates it.  Returns the server's representation of the functionIngress, and an error, if there is any.
func (c *FakeFunctionIngresses) Create(functionIngress *v1alpha2.FunctionIngress) (result *v1alpha2.FunctionIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(functioningressesResource, c.ns, functionIngress), &v1alpha2.FunctionIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.FunctionIngress), err
}

// Update takes the representation of a functionIngress and updates it. Returns the server's representation of the functionIngress, and an error, if there is any.
func (c *FakeFunctionIngresses) Update(functionIngress *v1alpha2.FunctionIngress) (result *v1alpha2.FunctionIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(functioningressesResource, c.ns, functionIngress), &v1alpha2.FunctionIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.FunctionIngress), err
}

// Delete takes name of the functionIngress and deletes it. Returns an error if one occurs.
func (c *FakeFunctionIngresses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(functioningressesResource, c.ns, name), &v1alpha2.FunctionIngress{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFunctionIngresses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(functioningressesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.FunctionIngressList{})
	return err
}

// Patch applies the patch and returns the patched functionIngress.
func (c *FakeFunctionIngresses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.FunctionIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(functioningressesResource, c.ns, name, pt, data, subresources...), &v1alpha2.FunctionIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.FunctionIngress), err
}
