/*
Copyright 2023 OpenFaaS Author(s)

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FunctionIngressStatusApplyConfiguration represents an declarative configuration of the FunctionIngressStatus type for use
// with apply.
type FunctionIngressStatusApplyConfiguration struct {
	Conditions []v1.Condition `json:"conditions,omitempty"`
}

// FunctionIngressStatusApplyConfiguration constructs an declarative configuration of the FunctionIngressStatus type for use with
// apply.
func FunctionIngressStatus() *FunctionIngressStatusApplyConfiguration {
	return &FunctionIngressStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *FunctionIngressStatusApplyConfiguration) WithConditions(values ...v1.Condition) *FunctionIngressStatusApplyConfiguration {
	for i := range values {
		b.Conditions = append(b.Conditions, values[i])
	}
	return b
}
