---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gateway
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: ingress-operator
      containers:
      - name: gateway
        image: functions/gateway:0.7.8-armhf
        imagePullPolicy: Always
        env:
        - name: functions_provider_url
          value: "http://localhost:8081/"
        - name: faas_nats_address
          value: "nats.openfaas"
        - name: faas_nats_port
          value: "4222"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 100Mi
      - name: operator
        image: functions/ingress-operator:0.7.1-armhf
        imagePullPolicy: Always
        command:
          - ./ingress-operator
          - -logtostderr
          - -v=2
        env:
        - name: function_namespace
          value: openfaas-fn
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          limits:
            memory: 100Mi
