---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-operator
  namespace: openfaas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-operator-rw
  namespace: openfaas
rules:
- apiGroups: ["openfaas.com"]
  resources: ["functioningresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["ingress"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-operator-rw
  namespace: openfaas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-operator-rw
subjects:
- kind: ServiceAccount
  name: ingress-operator
  namespace: openfaas
